# Práctica de la librería Numpy

En este notebook, se desarrollarán una serie de tareas utilizando la librería Numpy (Numerical Python).

Se proponen y documentan posibles formas de resolver los ejercicios, pero las mismas no son únicas.

Siempre es una buena idea verificar la [Documentación Oficial de Numpy](https://numpy.org/devdocs/user/index.html), donde es posible encontrar todo tipo de información referida a esta librería. Y si te quedas trabado, busca en Google "como hacer [algo] con Numpy". Hay enormes probabilidades de que esa pregunta ya haya sido respondida!

In [ ]:
# Importamos Numpy con su abreviación "np"
import numpy as np


In [ ]:
# Podemos crear arrays de una dimensión con la función np.array()
array_1d = np.array([1,2,3,4,5])

# O un array de dos dimensiones (bidimensional)
array_2d = np.array([[1,2,3],[4,5,6]])

# O un array de tres dimensiones (tridimensional)
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])


Para cada uno de estos arrays, podemos obtener sus propiedades, tales como su "forma", número de dimensiones, tipos de datos y tamaño.

In [ ]:
# Atributos del array unidimensional (forma, número de dimensiones, tipos de datos, tamaño, y tipo)
array_1d.shape, array_1d.ndim, array_1d.dtype, array_1d.size, type(array_1d)


((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [ ]:
# Atributos del array bidimensional
array_2d.shape, array_2d.ndim, array_2d.dtype, array_2d.size, type(array_2d)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [ ]:
# Atributos del array tridimensional
array_3d.shape, array_3d.ndim, array_3d.dtype, array_3d.size, type(array_3d)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [ ]:
# Importamos pandas como pd, y creamos un DataFrame a partir del array bidimensional
import pandas as pd
df = pd.DataFrame(array_2d)
df

0  1  2
0  1  2  3
1  4  5  6

In [ ]:
# Creamos un array de tamaño 4x3, formado únicamente por unos (1)
unos = np.ones((4,3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Creamos un array de tamaño 2x4x3, formado únicamente por ceros (0)
ceros = np.zeros((2,4,3))
ceros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# Creamos un array de números en el rango de 0 a 100, con un paso de 5
array_1d = np.arange(0, 100, 5)
array_1d

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (2, 5)
array_2d = np.random.randint(0, 10, size=(2,5))
array_2d

array([[8, 7, 1, 6, 2],
       [3, 0, 0, 5, 6]])

In [ ]:
# Creamos un array de números aleatorios decimales comprendidos en entre 0 y 1, de tamaño (3, 5)
array_2d = np.random.random((3,5))
array_2d

array([[0.53530164, 0.16161615, 0.55719611, 0.94744259, 0.86431996],
       [0.70880001, 0.40488249, 0.21852946, 0.42603002, 0.61405726],
       [0.95320195, 0.64849477, 0.90792482, 0.0992484 , 0.32140774]])

In [ ]:
# Establecemos la "semilla" de números aleatorios en 27
np.random.seed(28)

# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (3, 5)
array_4 = np.random.randint(0, 10, size=(3,5))
array_4


array([[1, 9, 5, 6, 4],
       [0, 3, 7, 0, 3],
       [7, 5, 8, 8, 2]])

¿Qué ocurre al correr la última celda nuevamente, a diferencia de las anteriores?

In [ ]:
# Encontramos los valores únicos del array_4
np.unique(array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Extraemos el elemento de índice 1 del array_4
array_4[1]

array([0, 3, 7, 0, 3])

In [ ]:
# Extraemos las primeras dos filas del array_4
array_4[:2]

array([[1, 9, 5, 6, 4],
       [0, 3, 7, 0, 3]])

In [ ]:
# Extraemos los dos primeros datos de las primeras dos filas del array_4
array_4[:2, :2]

array([[1, 9],
       [0, 3]])

In [ ]:
# Creamos dos arrays de tamaño 3x4: uno relleno de números aleatorios entre 0 y 10, y otro relleno de unos
array_5 = np.random.randint(0 ,10, (3,4))
array_6 = np.ones((3, 4))

In [ ]:
# invocamos el array_5
array_5

array([[8, 7, 1, 6],
       [2, 3, 0, 0],
       [5, 6, 4, 8]])

In [ ]:
# invocamos el array_6
array_6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Sumamos los dos arrays
array_5 + array_6

array([[9., 8., 2., 7.],
       [3., 4., 1., 1.],
       [6., 7., 5., 9.]])

In [ ]:
# Creamos ahora un array de tamaño (4,3) lleno de unos
array_7 = np.ones((4, 3))

In [ ]:
# Intentaremos sumar los arrays 6 y 7
array_6 + array_7

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

¿A qué se debe el error anterior? ¿Qué deberíamos tener en cuenta para que no suceda?

In [ ]:
# Entonces crearemos otro array de tamaño (4,3) lleno de unos
array_8 = np.ones((4,3))
array_8

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Restamos el array_8 al array_7
array_8 - array_7

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Creamos otros dos arrays de tamaño 3x3 con números aleatorios del 1 al 5
array_9 = np.random.randint(1, 5, (3, 3))
array_10 = np.random.randint(1, 5, (3, 3))

In [ ]:
# invocamos el array_9
array_9

array([[1, 2, 4],
       [3, 1, 4],
       [1, 1, 1]])

In [ ]:
# invocamos el array_10
array_10

array([[2, 2, 1],
       [4, 1, 2],
       [1, 1, 2]])

In [ ]:
# Multiplicamos los últimos dos arrays entre sí
array_9 * array_10

array([[ 2,  4,  4],
       [12,  1,  8],
       [ 1,  1,  2]])

In [ ]:
# Elevamos el array_9 al cuadrado
array_9 ** 2

array([[ 1,  4, 16],
       [ 9,  1, 16],
       [ 1,  1,  1]])

In [ ]:
# Buscamos la raíz cuadrada del array_10
np.sqrt(array_10)

array([[1.41421356, 1.41421356, 1.        ],
       [2.        , 1.        , 1.41421356],
       [1.        , 1.        , 1.41421356]])

In [ ]:
# Hallamos el promedio de los valores del array_9
array_9.mean()

2.0

In [ ]:
# Hallamos el valor máximo de los valores del array_9
array_9.max()

4

In [ ]:
# Hallamos el valor mínimo de los valores del array_9
array_9.min()

1

In [ ]:
# Cambiamos la forma del array_9 por una de 9x1, y lo almacenamos como array_11
array_11 = array_9.reshape((9, 1))

In [ ]:
# invocamos el array_11
array_11

array([[1],
       [2],
       [4],
       [3],
       [1],
       [4],
       [1],
       [1],
       [1]])

In [ ]:
# Transponemos el array_11
array_11.T

array([[1, 2, 4, 3, 1, 4, 1, 1, 1]])

In [ ]:
# Comparamos el array_9 y el array_10, para saber cuáles elementos del array_9 son mayores a los del array_10
array_12 = array_9 > array_10
array_12

array([[False, False,  True],
       [False, False,  True],
       [False, False, False]])

¿Qué tipos de datos forman parte del array de resultados?

In [ ]:
# Veamos sus nuevos tipos de datos
array_12.dtype

dtype('bool')

In [ ]:
# Alguno de los elementos del array_9 es igual su equivalente del array_10?
array_9 == array_10

array([[False,  True, False],
       [False,  True, False],
       [ True,  True, False]])

In [ ]:
# Comparamos nuevamente ambos arrays, en esta ocasión con >=
array_9 >= array_10

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True, False]])

In [ ]:
# Buscamos los elementos del array_9 que son mayores a 2
array_9 > 2

array([[False, False,  True],
       [ True, False,  True],
       [False, False, False]])

In [ ]:
# Ordenamos de menor a mayor los elementos dentro del array_9
np.sort(array_9)

array([[1, 2, 4],
       [1, 3, 4],
       [1, 1, 1]])